# Generated by Django 5.0.3 on 2024-04-03 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('textbook', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_creator',
            field=models.ForeignKey(help_text='The user who created this message.', on_delete=django.db.models.deletion.CASCADE, related_name='created_messages', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='code_questions',
            field=models.ManyToManyField(related_name='quiz', to='textbook.codequestion'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='exam_questions',
            field=models.ManyToManyField(related_name='quiz', to='textbook.examquestion'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='revision_questions',
            field=models.ManyToManyField(related_name='quiz', to='textbook.revisionquestion'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='sequence_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sequence', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='studynote',
            name='note_creator',
            field=models.ForeignKey(help_text='The student user who created this study note.', limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='studynotes', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='textbook.subject'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='textbook.subject'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.ForeignKey(help_text='The subject this message is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='textbook.subject'),
        ),
        migrations.AddField(
            model_name='assessmentschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schedule', to='textbook.subject'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='syllabus_content',
            field=models.ManyToManyField(to='textbook.syllabuscontent'),
        ),
        migrations.AddField(
            model_name='syllabusindicator',
            name='syllabus_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='textbook.syllabuscontent'),
        ),
        migrations.AddField(
            model_name='revisionquestion',
            name='syllabus_outcomes',
            field=models.ManyToManyField(related_name='rq_questions', to='textbook.syllabusoutcome'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='syllabus_outcomes',
            field=models.ManyToManyField(to='textbook.syllabusoutcome'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='syllabus_outcomes',
            field=models.ManyToManyField(related_name='eq_questions', to='textbook.syllabusoutcome'),
        ),
        migrations.AddField(
            model_name='codequestion',
            name='syllabus_outcomes',
            field=models.ManyToManyField(related_name='cq_questions', to='textbook.syllabusoutcome'),
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='syllabus_outcomes',
            field=models.ManyToManyField(related_name='assessment_task', to='textbook.syllabusoutcome'),
        ),
        migrations.AddField(
            model_name='syllabustopic',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='textbook.subject'),
        ),
        migrations.AddField(
            model_name='syllabusoutcome',
            name='syllabus_topics',
            field=models.ManyToManyField(related_name='outcomes', to='textbook.syllabustopic'),
        ),
        migrations.AddField(
            model_name='syllabuscontent',
            name='syllabus_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='textbook.syllabustopic'),
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='syllabus_topics',
            field=models.ManyToManyField(related_name='assessment_task', to='textbook.syllabustopic'),
        ),
        migrations.AddField(
            model_name='term',
            name='sequences',
            field=models.ManyToManyField(related_name='terms', to='textbook.sequence'),
        ),
        migrations.AddField(
            model_name='textbook',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook', to='textbook.subject'),
        ),
        migrations.AddField(
            model_name='textbookpage',
            name='page_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='revisionquestion',
            name='textbook_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rq_questions', to='textbook.textbookpage'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pages',
            field=models.ManyToManyField(to='textbook.textbookpage'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='textbook_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq_questions', to='textbook.textbookpage'),
        ),
        migrations.AddField(
            model_name='codequestion',
            name='textbook_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cq_questions', to='textbook.textbookpage'),
        ),
        migrations.AddField(
            model_name='textbooksection',
            name='section_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sections', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='textbookpage',
            name='sections',
            field=models.ManyToManyField(related_name='pages', to='textbook.textbooksection'),
        ),
        migrations.AddField(
            model_name='textbookslide',
            name='pages',
            field=models.ManyToManyField(related_name='slides', to='textbook.textbookpage'),
        ),
        migrations.AddField(
            model_name='textbookslide',
            name='slide_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slides', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='studynote',
            name='slide',
            field=models.ForeignKey(help_text='Select the slide this study note is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='studynotes', to='textbook.textbookslide'),
        ),
        migrations.AddField(
            model_name='textbooktopic',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='textbook.textbook'),
        ),
        migrations.AddField(
            model_name='textbooktopic',
            name='topic_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='textbooksection',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='textbook.textbooktopic'),
        ),
        migrations.AddField(
            model_name='revisionquestion',
            name='thinking_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rq_questions', to='textbook.thinkinglevel'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='thinking_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq_questions', to='textbook.thinkinglevel'),
        ),
        migrations.AddField(
            model_name='codequestion',
            name='thinking_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cq_questions', to='textbook.thinkinglevel'),
        ),
        migrations.AddField(
            model_name='week',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='textbook.term'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='textbook.week'),
        ),
    ]
