# Generated by Django 5.0.3 on 2024-04-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0003_alter_syllabustopic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabusoutcome',
            name='outcome_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
