# Generated by Django 5.0.3 on 2024-04-04 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0005_remove_syllabusoutcome_syllabus_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusoutcome',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='textbook.subject'),
            preserve_default=False,
        ),
    ]
