# Generated by Django 5.0.3 on 2024-04-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0006_syllabusoutcome_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabustopic',
            name='outcomes',
            field=models.ManyToManyField(related_name='topics', to='textbook.syllabusoutcome'),
        ),
    ]
