# Generated by Django 5.0.3 on 2024-04-16 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0010_remove_syllabusindicator_syllabus_outcomes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabustopic',
            old_name='syllabus_topic',
            new_name='syllabus_topic_name',
        ),
        migrations.AddField(
            model_name='syllabustopic',
            name='syllabus_topic_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='textbook.subject'),
        ),
    ]
