# Generated by Django 5.0.3 on 2024-04-19 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0011_rename_syllabus_topic_syllabustopic_syllabus_topic_name_and_more'),
        ('users', '0002_rename_firstname_userprofile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lesson', to='users.userprofile'),
        ),
    ]
