# Generated by Django 5.0.3 on 2024-04-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0013_remove_lesson_lesson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='textbook_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
